---
efiBootLoader: "grub"
kernel: "/boot/vmlinuz-linux"
img: "/boot/initramfs-linux.img"
fallback: "/boot/initramfs-linux-fallback.img"
timeout: "5"
kernelLine: "LarpOS Linux"
fallbackKernelLine: "LarpOS Linux (fallback)"
grubInstall: "grub-install"
grubMkconfig: "grub-mkconfig"
grubCfg: "/boot/grub/grub.cfg"
