# GRUB bootloader installation
efiBootLoader: "grub"

kernel: "/boot/vmlinuz-linux"
img: "/boot/initramfs-linux.img"
fallback: "/boot/initramfs-linux-fallback.img"

timeout: "5"

bootLoader:
    grubInstall: "grub-install"
    grubMkconfig: "grub-mkconfig"
    grubCfg: "/boot/grub/grub.cfg"
