# LarpOS partitioning defaults
defaultFileSystemType: "ext4"
efiFileSystemType: "fat32"
availableFileSystemTypes: ["ext4", "btrfs", "xfs"]
drawNestedPartitions: true
alwaysShowPartitionLabels: true
initialPartitioningChoice: "erase"
initialSwapChoice: "swap"
allowManualPartitioning: true
