# systemd services enabled on the installed system
services:
    - name: "greetd"
      runlevel: "multi-user.target"
    - name: "NetworkManager"
      runlevel: "multi-user.target"
    - name: "systemd-timesyncd"
      runlevel: "multi-user.target"
    - name: "fstrim.timer"
      runlevel: "timers.target"
