# LarpOS user settings for installed systems
defaultGroups:
    - wheel
    - users
    - audio
    - video
    - optical
    - storage
    - input
    - lp
    - uucp
    - rfkill
    - docker

autologinGroup:  autologin
doAutologin:     false
sudoersGroup:    wheel
setRootPassword: true
userShell:       /bin/zsh
