# LarpOS welcome requirements
requirements:
    requiredStorage:    15
    requiredMemory:     2048
    internetCheckUrl:   http://connectivity-check.archlinux.org

geonamesUrl: https://geoip.kde.org/v1/calamares
