# LarpOS live session users (created at boot by systemd-sysusers)
g docker - -
g rfkill - -
g liveuser - -
u liveuser - "LarpOS Live User" /home/liveuser /usr/bin/zsh
m liveuser wheel
m liveuser audio
m liveuser video
m liveuser optical
m liveuser storage
m liveuser input
m liveuser users
m liveuser lp
m liveuser uucp
m liveuser rfkill
m liveuser docker
