# LarpOS Calamares settings
modules-search: [ local ]

instances:
- id: fixgreetd
  module: shellprocess

sequence:
- show:
  - welcome
  - locale
  - keyboard
  - partition
  - users
  - summary
- exec:
  - partition
  - mount
  - unpackfs
  - machineid
  - fstab
  - locale
  - keyboard
  - localecfg
  - initcpio
  - users
  - shellprocess@fixgreetd
  - networkcfg
  - hwclock
  - services-systemd
  - packages
  - bootloader
  - umount

branding: larpos
prompt-install: true
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: false
