[General]
DisplayServer=wayland
GreeterEnvironment=QT_WAYLAND_SHELL_INTEGRATION=layer-shell-v1

[Wayland]
CompositorCommand=kwin_wayland --drm --no-lockscreen --locale1

[Autologin]
User=liveuser
Session=plasma
Relogin=false
